### PR TITLE
Update to 1.3.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like you need `setuptools_scm` at build time.

Also would be very curious how re-rendering goes with `1.4.2`. 😉

**Comment by nicoddemus** [comment]
> Looks like you need setuptools_scm at build time.

Yep. 😁 

> Also would be very curious how re-rendering goes with 1.4.2. 😉

That wasn't released yet, right? Just re-rendered the feedstock with `1.3.3`.

**Comment by nicoddemus** [comment]
Oh my bad, forgot to add `conda-forge` to my conda config.

No changes with `1.4.2` actually:

```
Re-rendered with conda-smithy 1.4.2.

No changes made. This feedstock is up-to-date.
```

**Comment by jakirkham** [comment]
Ok, was worried it was missing for some reason for a second. 😌

Yeah, there isn't any difference on what the re-rendering generated from `1.3.3`. Only changes in user interface.

Not a big deal to do it on this feedstock per se as it is re-rendered. Just curious if it helps the Linux VM situation at all. 😄

**Comment by nicoddemus** [comment]
> Not a big deal to do it on this feedstock per se as it is re-rendered. Just curious if it helps the Linux VM situation at all. 😄

Reverted the commit locally just to check it out:

```
vagrant@thdengops-ubuntu-14:~/pytest-mock-feedstock$ ~/miniconda3/bin/conda smithy rerender -c auto
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........
Fetching package metadata .........

Re-rendered with conda-smithy 1.4.2.

[detached HEAD 3bd1e56] MNT: Re-rendered with conda-smithy 1.4.2
 7 files changed, 56 insertions(+), 138 deletions(-)
 create mode 100755 ci_support/checkout_merge_commit.sh
 delete mode 100755 ci_support/upload_or_check_non_existence.py

These changes need to be pushed to github!
```

Looks nice!

**Comment by jakirkham** [comment]
This warms my heart. 😄

```
 create mode 100755 ci_support/checkout_merge_commit.sh
 delete mode 100755 ci_support/upload_or_check_non_existence.py
```

(with execute permissions)

**Comment by jakirkham** [comment]
Thanks for trying. :+1:

**Comment by nicoddemus** [comment]
My pleasure! 😄

**Comment by ocefpaf** [comment]
@nicoddemus can you rerender with the latest `conda-smithy`? We just fixed a bug that should get the Windows builds going again.

**Comment by nicoddemus** [comment]
@ocefpaf done, thanks for the ping!

**Pull request merged**
