### PR TITLE
Update to 1.2

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@nicoddemus I noticed that you sent the PR from this repo instead of a fork. That not only trigger the CIs twice but also uploads the package before the PR is merged. Sometimes that is not desirable since we can upload a broken package.

We are improving the docs to say that more explicitly: https://github.com/conda-forge/conda-smithy/pull/246/files

Feedback is welcomed!

**Comment by nicoddemus** [comment]
@ocefpaf oh OK, thanks, I wasn't aware of that. I will create branches in forks for future updates. :grin:

**Comment by ocefpaf** [comment]
> I wasn't aware of that.

Yeah, the problem is on our side and the docs we are always promising we will write... One day...

**Comment by nicoddemus** [comment]
No worries! Thanks a ton for the project, it is actually amazing the ecosystem you guys managed to create! :+1:

**Pull request merged**
