### PR TITLE
add bottom pytest version, pip check, simplify recipe

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- adds a bottom pin for `pytest` reflecting upstream `setup.py`
- adds `pip check` in test help catch _some_ similar changes in the future
- simplifies some yaml syntax, jinja usage

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by nicoddemus** [comment]
The test suite of the `3.7.0` release contains those two failures due to some messages that were changed in `pytest-7.1.0` (released after `pytest-mock 3.7.0`). 

This since then has been fixed in https://github.com/pytest-dev/pytest-mock/commit/0577f1ad051fb8d0da94ea22dcb02346d74064b2 in `master`, but has not been released yet.

So what is happening is that we are testing the old test suite with the new pytest, and recent changes in pytest (which occurred after the pytest-mock released) brakes two tests.

Let's go ahead and merge this, the PR is definitely an improvement and it should be OK by the time of the next pytest-mock release. 👍

**Review by nicoddemus — APPROVED** [review]

**Comment by bollwyvl** [comment]
Ok, thanks for the review! Whatever works for you!

**Comment by bollwyvl** [comment]
Oooh, good thing it failed: i see a glaring mistake in replacing `{{ version }}` with `1`, will open a new PR.

**Pull request merged**
